In [1]:
import torch

In [12]:
torch.manual_seed(0)
x = torch.randn(5, 10, 5, 5)

In [16]:
x_mean = x.mean(dim=[-1, -2], keepdim=True)
x.shape, x_mean.shape, (x - x_mean).shape

(torch.Size([5, 10, 5, 5]),
 torch.Size([5, 10, 1, 1]),
 torch.Size([5, 10, 5, 5]))

In [10]:
print(Ys[:, 0])
Ys

tensor([0.0273, 0.2194, 0.9384])


tensor([[0.0273, 0.6080],
        [0.2194, 0.0542],
        [0.9384, 0.1753]])

In [21]:
ys = Ys[:, 0]
yb = Ys[:, 1]

In [24]:
print(ys.shape, x_mean.shape, x.shape)

torch.Size([3]) torch.Size([5, 10, 1, 1]) torch.Size([5, 10, 5, 5])


In [40]:
x = torch.tensor([1, 2, 4])
print(x.shape)
print(x)
x.repeat(5, 1)

torch.Size([3])
tensor([1, 2, 4])


tensor([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]])